# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 947c8fbfb62bf8a8d0033230a860ecceea66617410cc8fcaffc6918f2a51bd1268ff114a3c3e7c50e2d13929107c16de89dd0e986b1bd2286e88890817e74fec

test:
  domain_name: example.com 
  secret_key_base: d30092d43bee9b00e12de46c96214f94571767c603017f7aa4bc3c572bd8eb77a446fbc7f89b962c5dbb5034d570c86717cc23a2e19920a8e80f818d740cf38d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
